export const shoaibData = {
  personal: {
    name: "Muhammad Shoaib",
    title: "Full Stack Developer & UI/UX Designer",
    tagline: "I Build Digital Experiences That Matter",
    secondTagline: "Turning Ideas Into Stunning Reality",
    email: "shoaib.dev@gmail.com",
    phone: "+92 300 1234567",
    whatsapp: "+92 300 1234567",
    location: "Karachi, Pakistan",
    fiverr: "https://fiverr.com/muhammadshoaib",
    upwork: "https://upwork.com/freelancers/shoaib",
    github: "https://github.com/muhammadshoaib",
    linkedin: "https://linkedin.com/in/muhammadshoaib",
    twitter: "https://twitter.com/muhammadshoaib",
    instagram: "https://instagram.com/muhammadshoaib",
  },
  stats: {
    yearsExperience: 5,
    projectsCompleted: 50,
    happyClients: 20,
    codeCommits: 2000,
    countriesServed: 10,
  },
  skills: {
    frontend: ["React.js", "Next.js", "TypeScript", "JavaScript", "HTML5", "CSS3", "Tailwind CSS", "Framer Motion", "Redux", "Vue.js"],
    backend: ["Node.js", "Express.js", "Python", "Django", "REST APIs", "GraphQL", "MongoDB", "PostgreSQL", "MySQL", "Firebase"],
    design: ["Figma", "Adobe XD", "Photoshop", "Illustrator", "After Effects", "Canva", "Framer", "Webflow", "Sketch", "Zeplin"],
    devops: ["Git & GitHub", "Docker", "AWS", "Vercel", "Netlify", "Linux", "VS Code", "Postman", "Jira", "Agile/Scrum"],
  },
  proficiency: [
    { skill: "React.js", percent: 95 },
    { skill: "Next.js", percent: 92 },
    { skill: "TypeScript", percent: 88 },
    { skill: "Node.js", percent: 85 },
    { skill: "UI/UX Design", percent: 90 },
    { skill: "Figma", percent: 88 },
    { skill: "MongoDB", percent: 82 },
    { skill: "Python", percent: 78 },
  ],
  projects: [
    {
      id: 1,
      title: "LuxEstate",
      subtitle: "Real Estate Platform",
      category: "Web App",
      description: "A premium property listing platform with advanced search, agent profiles, interactive maps, virtual tours, and complete property management dashboard.",
      fullDescription: "LuxEstate is a comprehensive real estate platform that revolutionizes property browsing and management. Built with Next.js 15 and TypeScript, it features advanced filtering, real-time property listings, interactive Leaflet.js maps, and a full-featured property management dashboard for agents.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Leaflet.js", "Recharts", "Framer Motion"],
      features: ["Advanced property search & filters", "Interactive Leaflet.js maps", "Agent profiles & dashboards", "Virtual property tours", "Real-time analytics", "Mobile-responsive design"],
      challenges: ["Implementing real-time map clustering for 1000+ properties", "Building complex filter system with URL state management", "Optimizing LCP for image-heavy listings"],
      color: "#915EFF",
      github: "https://github.com/M-Shoaib7/Luxestate_Realstate",
      live: "https://luxestate-realstate.vercel.app/",
      number: "01",
    },
    {
      id: 2,
      title: "MediBook Pro",
      subtitle: "Doctor Booking System",
      category: "Web App",
      description: "Full-featured healthcare platform with doctor profiles, real-time appointment booking, patient dashboard, medical records, and video consultation.",
      fullDescription: "MediBook Pro transforms healthcare accessibility with a sophisticated appointment management system. Features include real-time availability calendar, HIPAA-compliant record management, video consultation integration, prescription management, and detailed analytics dashboards.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Recharts", "date-fns", "Socket.io"],
      features: ["Real-time appointment booking", "Doctor & patient dashboards", "Medical records management", "Video consultation integration", "Prescription tracking", "Analytics & reporting"],
      challenges: ["Building HIPAA-compliant data architecture", "Real-time calendar sync across timezones", "Implementing WebRTC video consultations"],
      color: "#00D8FF",
      github: "https://github.com/M-Shoaib7/The_Doctor_Booking_App_Mediprobook",
      live: "https://the-doctor-booking-app-mediprobook.vercel.app/",
      number: "02",
    },
    {
      id: 3,
      title: "Bandage",
      subtitle: "Luxury Fashion E-Commerce",
      category: "E-Commerce",
      description: "World-class fashion e-commerce platform with mega menu, live search, cart drawer, wishlist, order tracking, and complete admin panel.",
      fullDescription: "Bandage is a premium luxury fashion e-commerce platform that delivers an editorial shopping experience. Features include animated mega navigation, intelligent live search, wishlist system, cart drawer with micro-animations, complete checkout flow, and a powerful admin dashboard.",
      tech: ["Next.js", "TypeScript", "Framer Motion", "Tailwind", "Recharts", "Stripe"],
      features: ["Animated mega navigation menu", "Intelligent live search", "Cart drawer with animations", "Wishlist & favorites", "Order tracking system", "Admin dashboard & analytics"],
      challenges: ["Building performant mega menu with 500+ products", "Implementing optimistic UI updates for cart", "Creating editorial-style product pages"],
      color: "#FF6B9D",
      github: "https://github.com/M-Shoaib7/Bandage_E_Commerce_Store",
      live: "https://bandage-e-commerce-store-gfpo.vercel.app/",
      number: "03",
    },
    {
      id: 4,
      title: "EduNova LMS",
      subtitle: "Learning Management System",
      category: "Web App",
      description: "Enterprise LMS with video lessons, quiz engine, progress tracking, certificates, instructor dashboard, and student analytics.",
      fullDescription: "EduNova is an enterprise-grade Learning Management System designed for modern education. Built with scalability in mind, it supports video streaming, interactive quizzes, automatic certificate generation, instructor analytics, and a gamified student experience.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Recharts", "Framer Motion", "FFmpeg"],
      features: ["Video lessons with progress tracking", "Interactive quiz engine", "Automatic certificate generation", "Instructor & student dashboards", "Gamification & badges", "Analytics & reporting"],
      challenges: ["Implementing adaptive video streaming", "Building real-time quiz engine with anti-cheat", "Generating PDF certificates dynamically"],
      color: "#915EFF",
      github: "https://github.com/M-Shoaib7/EduNova_Education",
      live: "https://edu-nova-education.vercel.app/",
      number: "04",
    },
    {
      id: 5,
      title: "Employee Management System ",
      subtitle: "Premium Employee Management System Website",
      category: "Web App",
      description: "Stunning employee management website with online management tools, transparent payroll, mobile-first design, and premium editorial design.",
      fullDescription: "Employee Management System is a premium employee management website that provides online management tools, transparent payroll, mobile-first design, and premium editorial design.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Framer Motion", "Sanity CMS"],
      features: ["Animated menu showcase", "Online ordering system", "Table reservation system", "Chef's specials showcase", "Catering inquiry form", "Mobile-first design"],
      challenges: ["Creating cinematic scroll experiences for menu items", "Building real-time table availability system", "Optimizing image-heavy pages for Core Web Vitals"],
      color: "#FFD700",
      github: "https://github.com/M-Shoaib7/Employee_Management_System",
      live: "https://employee-management-system-umber-seven.vercel.app/dashboard",
      number: "05",
    },
    {
      id: 6,
      title: "ResumeForge",
      subtitle: "AI Resume Builder",
      category: "SaaS",
      description: "Professional resume builder with 25+ templates, AI writing suggestions, ATS scoring, PDF download, and job application tracker.",
      fullDescription: "ResumeForge is a comprehensive SaaS platform that helps job seekers create standout resumes. Features AI-powered content suggestions, ATS compatibility scoring, 25+ professionally designed templates, live preview, PDF export, and a job application tracker.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Framer Motion", "jsPDF", "OpenAI"],
      features: ["25+ professional templates", "AI writing suggestions", "ATS compatibility scoring", "Live preview & PDF export", "Job application tracker", "Multiple export formats"],
      challenges: ["Building pixel-perfect PDF generation from HTML", "Implementing ATS scoring algorithm", "Creating real-time collaborative editing"],
      color: "#00D8FF",
      github: "https://github.com/M-Shoaib7/Forge_Resume_Maker",
      live: "https://forge-resume-maker.vercel.app/",
      number: "06",
    },
    {
      id: 7,
      title: "Personal Finance Tracker",
      subtitle: "Personal Finance Management System",
      category: "SaaS",
      description: "Professional Finance Tracker with Amazing Dashboard, Who Can track everything like expenses, income, assets, liabilities, and more.",
      fullDescription: "Personal Finance Tracker is a comprehensive SaaS platform that helps users track their personal finances. Features a user-friendly dashboard, expense tracking, budgeting, and more.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Framer Motion", "jsPDF", "OpenAI"],
      features: ["Track expenses, income, assets, liabilities"],
      challenges: ["Building pixel-perfect PDF generation from HTML", "Implementing ATS scoring algorithm", "Creating real-time collaborative editing"],
      color: "#915EFF",
      github: "https://github.com/M-Shoaib7/FinTrack_Personal_Finance_Tracker",
      live: "https://fin-track-personal-finance-tracker-one.vercel.app/",
      number: "07",
    },
    {
      id: 8,
      title: "Drive Karachi Rent a Car",
      subtitle: "Car renal website",
      category: "SaaS",
      description: "We provide a hassle-free car rental experience for our clients. Our platform connects you with a wide range of vehicles to suit your needs, making it easy to book a car for your trip.",
      fullDescription: "For our clients, we provide a hassle-free car rental experience. Our platform connects you with a wide range of vehicles to suit your needs, making it easy to book a car for your trip.",
      tech: ["Next.js", "TypeScript", "Tailwind", "Framer Motion", "jsPDF", "OpenAI"],
      features: ["Track expenses, income, assets, liabilities"],
      challenges: ["Building pixel-perfect PDF generation from HTML", "Implementing ATS scoring algorithm", "Creating real-time collaborative editing"],
      color: "#FF6B9D",
      github: "https://github.com/M-Shoaib7/Drive_Karachi_CarRental",
      live: "https://drive-karachi-car-rental.vercel.app/",
      number: "08",
    },
  ],
  experience: [
    {
      id: 1,
      period: "2022 — Present",
      role: "Senior Full Stack Developer",
      company: "Freelance / Self-Employed",
      type: "Remote",
      icon: "briefcase",
      side: "left",
      bullets: [
        "Built 20+ premium web applications for international clients",
        "Specialized in Next.js, React, TypeScript, and Node.js development",
        "Delivered projects for clients in US, UK, UAE, and Pakistan",
        "Maintained 5★ rating on Fiverr with 100% client satisfaction",
      ],
    },
    {
      id: 2,
      period: "2020 — 2022",
      role: "Full Stack Developer",
      company: "Tech Startup, Karachi",
      type: "On-site",
      icon: "briefcase",
      side: "left",
      bullets: [
        "Developed and maintained multiple client-facing web applications",
        "Led frontend development using React.js and Next.js",
        "Collaborated with design team to implement pixel-perfect UIs",
        "Improved application performance by 60% through optimization",
      ],
    },
    {
      id: 3,
      period: "2019 — 2020",
      role: "Junior Web Developer",
      company: "Digital Agency, Karachi",
      type: "On-site",
      icon: "briefcase",
      side: "left",
      bullets: [
        "Built responsive websites using HTML, CSS, JavaScript",
        "Assisted senior developers in React.js projects",
        "Designed UI mockups using Figma",
      ],
    },
  ],
  education: [
    {
      id: 4,
      period: "2016 — 2020",
      degree: "Bachelor's in Computer Science",
      institution: "University of Karachi",
      location: "Karachi, Pakistan",
      gpa: "3.7/4.0",
      distinction: true,
      icon: "graduation-cap",
      side: "right",
    },
    {
      id: 5,
      period: "2023",
      degree: "Meta Front-End Developer Certificate",
      institution: "Coursera / Meta",
      honor: "Completed with Honors",
      icon: "award",
      side: "right",
    },
    {
      id: 6,
      period: "2022",
      degree: "AWS Cloud Practitioner",
      institution: "Amazon Web Services",
      icon: "cloud",
      side: "right",
    },
  ],
  services: [
    {
      id: 1,
      icon: "💻",
      title: "Full Stack Development",
      description: "End-to-end web application development from design to deployment. React, Next.js, Node.js, databases — all handled.",
      price: "PKR 50,000",
      color: "#915EFF",
      features: ["Responsive Design", "Fast Performance", "SEO Optimized", "Clean Code"],
    },
    {
      id: 2,
      icon: "🎨",
      title: "UI/UX Design",
      description: "Beautiful, intuitive interface design that converts visitors into customers. Figma prototypes to pixel-perfect implementation.",
      price: "PKR 25,000",
      color: "#FF6B9D",
      features: ["User Research", "Wireframing", "Prototyping", "Design Systems"],
    },
    {
      id: 3,
      icon: "🛍️",
      title: "E-Commerce Solutions",
      description: "Complete online store development with payment integration, inventory management, and admin dashboard.",
      price: "PKR 80,000",
      color: "#00D8FF",
      features: ["Payment Integration", "Inventory Mgmt", "Admin Panel", "Order Tracking"],
    },
    {
      id: 4,
      icon: "📊",
      title: "Dashboard & SaaS Apps",
      description: "Complex data dashboards, admin panels, and SaaS applications with real-time data, charts, and analytics.",
      price: "PKR 70,000",
      color: "#FFD700",
      features: ["Real-time Data", "Interactive Charts", "Role Management", "API Integration"],
    },
    {
      id: 5,
      icon: "📱",
      title: "Mobile Development",
      description: "Cross-platform mobile apps using React Native. iOS and Android from a single codebase.",
      price: "PKR 60,000",
      color: "#915EFF",
      features: ["iOS & Android", "Push Notifications", "Offline Support", "App Store Deploy"],
    },
    {
      id: 6,
      icon: "🚀",
      title: "Tech Consulting",
      description: "Architecture planning, code review, performance optimization, and technical guidance for your project.",
      price: "PKR 5,000/hr",
      color: "#00D8FF",
      features: ["Architecture Review", "Code Audit", "Performance Tips", "Tech Stack Choice"],
    },
  ],
  testimonials: [
    {
      id: 1,
      avatar: "AK",
      name: "Ahmed Khan",
      title: "CEO, TechStart Dubai",
      country: "🇦🇪",
      rating: 5,
      platform: "Upwork Verified",
      review: "Muhammad Shoaib is an exceptional developer. He built our entire SaaS platform from scratch in record time. The code quality, attention to detail, and communication were all outstanding. Highly recommended!",
      project: "Real Estate Dashboard",
      color: "#915EFF",
    },
    {
      id: 2,
      avatar: "SJ",
      name: "Sarah Johnson",
      title: "Marketing Director, NY",
      country: "🇺🇸",
      rating: 5,
      platform: "Fiverr Top Rated",
      review: "Absolutely incredible work! Shoaib transformed our outdated website into a modern masterpiece. The animations and user experience are beyond what we imagined. Will definitely hire again.",
      project: "E-Commerce Website",
      color: "#FF6B9D",
    },
    {
      id: 3,
      avatar: "BM",
      name: "Bilal Malik",
      title: "Startup Founder, Lahore",
      country: "🇵🇰",
      rating: 5,
      platform: "Direct Client",
      review: "Working with Shoaib was the best decision for our startup. He delivered a complete web application on time, within budget, and exceeded every expectation. The UI is stunning!",
      project: "LMS Platform",
      color: "#00D8FF",
    },
    {
      id: 4,
      avatar: "JW",
      name: "James Williams",
      title: "Product Manager, London",
      country: "🇬🇧",
      rating: 5,
      platform: "LinkedIn Client",
      review: "Shoaib is a rare find — he combines top-tier technical skills with an eye for beautiful design. Our dashboard app got compliments from every single stakeholder.",
      project: "Analytics Dashboard",
      color: "#FFD700",
    },
    {
      id: 5,
      avatar: "FR",
      name: "Fatima Riaz",
      title: "Business Owner, Karachi",
      country: "🇵🇰",
      rating: 5,
      platform: "Direct Client",
      review: "I was amazed by the quality of work and speed of delivery. My e-commerce store looks better than any competitor's. Sales have increased 40% since the new website launched!",
      project: "Fashion Store",
      color: "#FF6B9D",
    },
    {
      id: 6,
      avatar: "DC",
      name: "David Chen",
      title: "CTO, Singapore",
      country: "🇸🇬",
      rating: 5,
      platform: "Upwork",
      review: "Shoaib's technical knowledge is impressive. He suggested solutions I hadn't even considered and the final product was rock solid. Will be working with him on our next project.",
      project: "Healthcare Platform",
      color: "#00D8FF",
    },
    {
      id: 7,
      avatar: "LH",
      name: "Layla Hassan",
      title: "Restaurant Owner, UAE",
      country: "🇦🇪",
      rating: 5,
      platform: "Direct Client",
      review: "Our restaurant website is now the talk of the town! Shoaib created something truly beautiful. The online ordering system works flawlessly. Couldn't be happier!",
      project: "Restaurant Website",
      color: "#FFD700",
    },
    {
      id: 8,
      avatar: "RM",
      name: "Robert Martinez",
      title: "HR Director, Canada",
      country: "🇨🇦",
      rating: 5,
      platform: "Fiverr",
      review: "The resume builder platform Shoaib built for us is phenomenal. It's been praised by thousands of users. He understood our vision perfectly and delivered beyond expectations.",
      project: "Resume Builder SaaS",
      color: "#915EFF",
    },
  ],
  blogPosts: [
    {
      id: 1,
      slug: "building-world-class-portfolio-nextjs-15",
      title: "Building a World-Class Portfolio with Next.js 15",
      excerpt: "Everything you need to know about creating a stunning portfolio that lands clients — from animations to performance optimization.",
      category: "Tutorial",
      date: "Feb 2024",
      readTime: "8 min read",
      color: "#915EFF",
    },
    {
      id: 2,
      slug: "why-developers-should-learn-ux-design",
      title: "Why Every Developer Should Learn UI/UX Design",
      excerpt: "The intersection of code and design is where the magic happens. Here's why learning design made me a better developer.",
      category: "Opinion",
      date: "Jan 2024",
      readTime: "6 min read",
      color: "#00D8FF",
    },
    {
      id: 3,
      slug: "mastering-framer-motion-advanced-animations",
      title: "Mastering Framer Motion: Advanced Animations Guide",
      excerpt: "Deep dive into Framer Motion's most powerful features — gestures, layout animations, and shared element transitions.",
      category: "Tutorial",
      date: "Dec 2023",
      readTime: "12 min read",
      color: "#FF6B9D",
    },
    {
      id: 4,
      slug: "freelancer-to-five-figure-month",
      title: "From Freelancer to 5-Figure Month: My Journey",
      excerpt: "How I went from making $200/month on Fiverr to consistently hitting $10,000+ months — the strategies that actually work.",
      category: "Journey",
      date: "Nov 2023",
      readTime: "10 min read",
      color: "#FFD700",
    },
    {
      id: 5,
      slug: "top-10-nextjs-best-practices-2024",
      title: "Top 10 Next.js Best Practices in 2024",
      excerpt: "Performance, security, and developer experience tips every Next.js developer needs to know in 2024.",
      category: "Tutorial",
      date: "Oct 2023",
      readTime: "7 min read",
      color: "#915EFF",
    },
    {
      id: 6,
      slug: "how-i-built-50-projects-in-5-years",
      title: "How I Built 50 Projects in 5 Years",
      excerpt: "The productivity systems, learning strategies, and mindset shifts that helped me ship 50 real-world projects.",
      category: "Journey",
      date: "Sep 2023",
      readTime: "9 min read",
      color: "#00D8FF",
    },
  ],
};
